# -*- coding: utf-8 -*-
"""artisan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EeYKOcMq0-fFdzMvJU0AASCLu_5_LcM2
"""

!pip install -q -U transformers tokenizers peft trl bitsandbytes datasets accelerate huggingface_hub sentencepiece

from google.colab import userdata
from huggingface_hub import login

# Retrieve your secret named 'artisan'
token = userdata.get('artisan')
login(token=token)
print("✅ Successfully authenticated with Hugging Face!")

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"

print("⏳ Loading Qwen2.5-1.5B-Instruct & Tokenizer in 4-bit...")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)
model.config.use_cache = False

gpu_ram = torch.cuda.memory_allocated() / (1024 ** 3)
print(f"✅ Qwen2.5-1.5B loaded! VRAM used: {gpu_ram:.2f} GB (fits Colab free T4)")

import pandas as pd
from datasets import Dataset
import re
import random

print("⏳ Fetching real Indian Products dataset & building tri-lingual dataset...")

# 1. Download the real Flipkart Indian Products dataset
url = "https://huggingface.co/datasets/jason1966/PromptCloudHQ_flipkart-products/resolve/main/flipkart_com-ecommerce_sample.csv"
df = pd.read_csv(url)

# 2. Comprehensive Indian Artisan & Handloom Keyword Taxonomy
CRAFT_KEYWORDS = [
    # General terms
    "handcrafted", "handmade", "hand-made", "handwoven", "hand-woven",
    "handloom", "artisan", "craft", "traditional", "heritage", "ethnic",
    "handpainted", "hand-painted", "handcarved", "hand-carved", "hand-embroidered",
    # Textiles & Sarees
    "khadi", "chanderi", "banarasi", "kanjeevaram", "paithani", "tussar",
    "ikkat", "ikat", "bandhani", "chikankari", "phulkari", "kalamkari",
    "ajrakh", "patola", "sambalpuri", "kota doria", "jamdani", "dupatta",
    "saree", "sari", "shawl", "pure silk", "cotton", "jute", "zari", "zardozi",
    # Metals & Brassware
    "brass", "copper", "bronze", "dhokra", "dokra", "bidri", "meenakari",
    "kansa", "filigree", "diya", "samai", "vilakku", "uruli", "oil lamp",
    # Pottery & Clay
    "terracotta", "clay", "pottery", "blue pottery", "ceramic", "earthenware",
    "kulhad", "matka", "handi", "surahi",
    # Wood, Bamboo & Cane
    "sheesham", "rosewood", "teak", "sandalwood", "wooden", "channapatna",
    "bamboo", "cane", "jute bag", "wooden box", "wooden toy",
    # Folk Art & Jewelry
    "madhubani", "warli", "pattachitra", "tanjore", "kolhapuri", "kundan"
]

pattern = re.compile("|".join([re.escape(kw) for kw in CRAFT_KEYWORDS]), re.IGNORECASE)

def matches_craft(row):
    text = f"{row.get('product_name', '')} {row.get('product_category_tree', '')} {row.get('product_specifications', '')}"
    return bool(pattern.search(str(text)))

craft_mask = df['description'].notna() & df['product_name'].notna() & df.apply(matches_craft, axis=1)
craft_df = df[craft_mask].copy()

# Clean descriptions
def clean_text(text):
    text = re.sub(r'<.*?>', '', str(text))
    return re.sub(r'\s+', ' ', text).strip()

craft_df['clean_desc'] = craft_df['description'].apply(clean_text)
craft_df['clean_name'] = craft_df['product_name'].apply(clean_text)
craft_df = craft_df[(craft_df['clean_desc'].str.len() >= 80) & (craft_df['clean_desc'].str.len() <= 500)]

print(f"✅ Filtered {len(craft_df)} authentic Indian craft products from dataset!")

# 3. Build Tri-Lingual Dataset (English, Hindi, Marathi)
trilingual_samples = []

# System Prompts aligned with Table 007 specification
SYSTEM_PROMPTS = {
    "en": (
        "You are an expert e-commerce catalog specialist for traditional Indian artisans and handicrafts. "
        "Transform informal spoken artisan input into a polished, compelling, customer-ready product description. "
        "Only use facts mentioned by the artisan."
    ),
    "hi": (
        "आप पारंपरिक भारतीय कारीगरों और हस्तशिल्प के लिए ई-कॉमर्स विशेषज्ञ हैं। "
        "कारीगर की अनौपचारिक बोली से एक आकर्षक, प्रामाणिक और ग्राहक-तैयार उत्पाद विवरण तैयार करें। "
        "केवल बताए गए तथ्यों का उपयोग करें।"
    ),
    "mr": (
        "You are an expert e-commerce catalog specialist for traditional Indian artisans. "
        "Transform informal spoken Marathi artisan input into a polished, compelling product description "
        "honoring traditional craft heritage. Only use facts mentioned by the artisan."
    )
}

# Spoken templates reflecting natural artisan speech in each language
for idx, row in craft_df.iterrows():
    name = row['clean_name']
    desc = row['clean_desc']
    price = row.get('retail_price', '')
    price_val = int(price) if pd.notna(price) and price > 0 else 0

    # Assign across languages to ensure balanced multi-lingual training
    lang_cycle = ["en", "hi", "mr"][idx % 3]

    if lang_cycle == "en":
        price_str = f", price is ₹{price_val}" if price_val else ""
        speech_input = f"This is {name}{price_str}, handmade traditional Indian craft."
        output_text = desc
        sys_prompt = SYSTEM_PROMPTS["en"]

    elif lang_cycle == "hi":
        price_str = f", कीमत ₹{price_val} है" if price_val else ""
        speech_input = f"यह {name} है{price_str}, हाथ से बना हुआ पारंपरिक सामान।"
        # Rich Hindi artisan catalog description
        output_text = f"कुशल कारीगरों द्वारा हस्तनिर्मित {name}। यह पारंपरिक भारतीय शिल्प कौशल का उत्कृष्ट नमूना है, जो टिकाऊपन और प्रामाणिक कारीगरी को दर्शाता है।"
        sys_prompt = SYSTEM_PROMPTS["hi"]

    elif lang_cycle == "mr":
        price_str = f", किंमत ₹{price_val} आहे" if price_val else ""
        speech_input = f"हे {name} आहे{price_str}, हातांनी बनवलेले पारंपरिक भारतीय हस्तकला उत्पादन."
        output_text = f"स्थानिक कारागिरांनी हाताने तयार केलेले {name}. हे पारंपरिक कारागिरी आणि अस्सल भारतीय संस्कृतीचे प्रतीक आहे."
        sys_prompt = SYSTEM_PROMPTS["mr"]

    trilingual_samples.append({
        "lang": lang_cycle,
        "system": sys_prompt,
        "user": speech_input,
        "assistant": output_text
    })

random.seed(42)
random.shuffle(trilingual_samples)

print(f"🎉 Generated {len(trilingual_samples)} Tri-Lingual Artisan training samples:")
print(f"   - English (en) : {sum(1 for s in trilingual_samples if s['lang'] == 'en')}")
print(f"   - Hindi (hi)   : {sum(1 for s in trilingual_samples if s['lang'] == 'hi')}")
print(f"   - Marathi (mr) : {sum(1 for s in trilingual_samples if s['lang'] == 'mr')}")

# 4. Format with Qwen's Native ChatML Template
def apply_chatml(sample):
    messages = [
        {"role": "system", "content": sample["system"]},
        {"role": "user", "content": sample["user"]},
        {"role": "assistant", "content": sample["assistant"]}
    ]
    return {"text": tokenizer.apply_chat_template(messages, tokenize=False)}

train_dataset = Dataset.from_list(trilingual_samples).map(apply_chatml)

print("\n--- Sample Tri-Lingual Prompt (ChatML) ---")
print(train_dataset[0]["text"][:350] + "...\n")

from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

# Prepare 4-bit model for gradient training
model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
# Trainable params will show ~1.5% — very fast and memory efficient!

import torch
from trl import SFTTrainer, SFTConfig

# 1. Disable cache for training
model.config.use_cache = False

# 2. Ensure all trainable LoRA parameters are float32 (fixes T4 BFloat16)
for name, param in model.named_parameters():
    if param.requires_grad or param.dtype == torch.bfloat16:
        param.data = param.data.to(torch.float32)

# 3. Clean dataset columns
clean_train_dataset = train_dataset.select_columns(["text"])

# 4. Full Dataset Accuracy Training (Batch size 4 = faster GPU throughput)
training_args = SFTConfig(
    output_dir="./qwen-artisan-adapter",
    dataset_text_field="text",
    max_length=512,
    num_train_epochs=1,              # 1 full pass over all 5,098 samples = maximum craft diversity without overfitting
    per_device_train_batch_size=4,   # 4 samples per forward pass (faster utilization)
    gradient_accumulation_steps=2,   # Effective batch size = 8
    learning_rate=2e-4,
    fp16=False,
    bf16=False,
    logging_steps=10,
    save_strategy="no",
    report_to="none"
)

# 5. Initialize SFTTrainer
trainer = SFTTrainer(
    model=model,
    train_dataset=clean_train_dataset,
    processing_class=tokenizer,
    args=training_args,
)

print("🚀 Starting full-dataset training (batch_size=4) on Colab T4 GPU...")
trainer.train()

# 6. Save the trained LoRA adapter & tokenizer to disk
trainer.save_model("./qwen-artisan-adapter")
tokenizer.save_pretrained("./qwen-artisan-adapter")

# 7. Restore use_cache for generation testing
model.config.use_cache = True
model.eval()

print("\n🎉 Full dataset training successfully completed!")
print("✅ LoRA adapter saved locally at './qwen-artisan-adapter'!")

import torch

def generate_artisan_description(speech_input: str, lang: str = "en") -> str:
    system_prompts = {
        "en": (
            "You are an expert e-commerce catalog specialist for traditional Indian artisans and handicrafts. "
            "Transform informal spoken artisan input into a polished, compelling, customer-ready product description. "
            "Only use facts mentioned by the artisan."
        ),
        "hi": (
            "आप पारंपरिक भारतीय कारीगरों और हस्तशिल्प के लिए ई-कॉमर्स विशेषज्ञ हैं। "
            "कारीगर की अनौपचारिक बोली से एक आकर्षक, प्रामाणिक और ग्राहक-तैयार उत्पाद विवरण तैयार करें। "
            "केवल बताए गए तथ्यों का उपयोग करें।"
        ),
        "mr": (
            "You are an expert e-commerce catalog specialist for traditional Indian artisans. "
            "Transform informal spoken Marathi artisan input into a polished, compelling product description "
            "honoring traditional craft heritage. Only use facts mentioned by the artisan."
        )
    }

    messages = [
        {"role": "system", "content": system_prompts.get(lang, system_prompts["en"])},
        {"role": "user", "content": speech_input}
    ]

    # Format using Qwen's ChatML template
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=150,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    # Decode only the generated response
    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]
    return tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()


print("=" * 60)
print("TEST 1 — English (Handloom Chanderi Saree)")
print("=" * 60)
input_en = "This is a handloom chanderi silk saree with gold zari border, 2800 rupees, traditional weave."
print("🎙️ Artisan Spoke :", input_en)
print("✨ Generated Desc:", generate_artisan_description(input_en, lang="en"))

print("\n" + "=" * 60)
print("TEST 2 — Hindi (Brass Peacock Diya)")
print("=" * 60)
input_hi = "यह हाथ से बना पीतल का मयूर दीया है, पूजा के लिए, 750 रुपये, शुद्ध पीतल।"
print("🎙️ Artisan Spoke :", input_hi)
print("✨ Generated Desc:", generate_artisan_description(input_hi, lang="hi"))

print("\n" + "=" * 60)
print("TEST 3 — Marathi (Paithani Saree)")
print("=" * 60)
input_mr = "हे हातांनी विणलेले पैठणी साडी आहे, मोर नक्षी, 3500 रुपये."
print("🎙️ Artisan Spoke :", input_mr)
print("✨ Generated Desc:", generate_artisan_description(input_mr, lang="mr"))

print("\n" + "=" * 60)
print("TEST 4 — Conversational / Messy Input with Fillers")
print("=" * 60)
input_messy = "um... this is just a small handmade jute bag, around 200 rs, eco friendly."
print("🎙️ Artisan Spoke :", input_messy)
print("✨ Generated Desc:", generate_artisan_description(input_messy, lang="en"))

from huggingface_hub import HfApi
from google.colab import files
import shutil

# 1. Auto-detect your username from your 'artisan' token
api = HfApi()
user_info = api.whoami()
hf_username = user_info["name"]
repo_id = f"{hf_username}/qwen-artisan-description"

print(f"⏳ Uploading LoRA adapter to Hugging Face: {repo_id}...")

# 2. Push to Hugging Face Hub (100% Free Public Repo)
model.push_to_hub(repo_id, private=False)
tokenizer.push_to_hub(repo_id, private=False)

print("\n🎉 Model is officially LIVE on Hugging Face!")
print(f"🔗 Public URL: https://huggingface.co/{repo_id}")
print(f"⚡ Repo ID for backend: {repo_id}")

# 3. Download a zip directly to your computer as an offline backup
print("\n📦 Zipping adapter for local backup...")
shutil.make_archive("qwen-artisan-adapter", 'zip', "./qwen-artisan-adapter")
files.download("qwen-artisan-adapter.zip")
print("✅ Downloading 'qwen-artisan-adapter.zip' to your laptop!")

!pip install -q -U torchao

import nest_asyncio; nest_asyncio.apply()
import torch, subprocess, threading, time, re
from fastapi import FastAPI
from pydantic import BaseModel
from typing import Optional
import uvicorn
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

# ── Load Model ────────────────────────────────────────────────
BASE_MODEL = "Qwen/Qwen2.5-1.5B-Instruct"
LORA_REPO  = "harshvdn2/qwen-artisan-description"

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)

print("Loading base model...")
base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL, torch_dtype=torch.float16, device_map="auto", trust_remote_code=True
)

print("Merging LoRA adapter...")
model = PeftModel.from_pretrained(base_model, LORA_REPO)
model.eval()
print("Model ready!")

# ── FastAPI App ───────────────────────────────────────────────
app = FastAPI()

SYSTEM_PROMPTS = {
    "en": "You are an expert e-commerce catalog specialist for traditional Indian artisans. Transform informal artisan speech into a polished, compelling English product description. Only use facts mentioned by the artisan. Output only the description.",
    "hi": "You are an expert e-commerce catalog specialist for traditional Indian artisans. The artisan spoke in Hindi. Transform their informal spoken input into a polished product description written IN ENGLISH ONLY. Output only the English description.",
    "mr": "You are an expert e-commerce catalog specialist for traditional Indian artisans. The artisan spoke in Marathi. Transform their informal spoken Marathi input into a polished product description written IN ENGLISH ONLY. Output only the English description.",
}

class Req(BaseModel):
    inputs: str
    parameters: Optional[dict] = None
    lang: Optional[str] = "en"

@app.get("/health")
def health():
    return {"status": "ok", "model": LORA_REPO}

@app.post("/generate")
def generate(req: Req):
    lang = req.lang or "en"
    sys_prompt = SYSTEM_PROMPTS.get(lang, SYSTEM_PROMPTS["en"])
    chatml = (
        f"<|im_start|>system\n{sys_prompt}<|im_end|>\n"
        f"<|im_start|>user\n{req.inputs.strip()}<|im_end|>\n"
        f"<|im_start|>assistant\n"
    )
    params = req.parameters or {}
    inp = tokenizer(chatml, return_tensors="pt").to(model.device)
    with torch.no_grad():
        out = model.generate(
            **inp,
            max_new_tokens=params.get("max_new_tokens", 150),
            temperature=params.get("temperature", 0.7),
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
        )
    text = tokenizer.decode(
        out[0][inp["input_ids"].shape[1]:], skip_special_tokens=True
    ).strip()
    return [{"generated_text": text}]

# ── Start server in background thread ─────────────────────────
server_thread = threading.Thread(
    target=lambda: uvicorn.run(app, host="0.0.0.0", port=8080), daemon=True
)
server_thread.start()
time.sleep(2)
print("Server running on port 8080")

# ── Cloudflare Tunnel (no account needed) ─────────────────────
import subprocess, os
os.system("wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared && chmod +x cloudflared")

proc = subprocess.Popen(
    ["./cloudflared", "tunnel", "--url", "http://localhost:8080"],
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT
)

print("Waiting for tunnel...")
for line in proc.stdout:
    line = line.decode()
    match = re.search(r"https://[a-z0-9\-]+\.trycloudflare\.com", line)
    if match:
        url = match.group(0)
        print("\n" + "="*60)
        print("  PASTE THIS INTO YOUR .env FILE:")
        print(f"  QWEN_API_URL={url}/generate")
        print("="*60 + "\n")
        break

import asyncio, re, subprocess, os

# Fix for Python 3.13 + nest_asyncio — use asyncio task instead of thread
config = uvicorn.Config(app, host="0.0.0.0", port=8080, loop="none")
server = uvicorn.Server(config)

loop = asyncio.get_event_loop()
loop.create_task(server.serve())
print("Server started on port 8080")

# Reuse same cloudflare tunnel (already downloaded)
proc = subprocess.Popen(
    ["./cloudflared", "tunnel", "--url", "http://localhost:8080"],
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT
)

print("Getting tunnel URL...")
for line in proc.stdout:
    line = line.decode()
    match = re.search(r"https://[a-z0-9\-]+\.trycloudflare\.com", line)
    if match:
        url = match.group(0)
        print("\n" + "="*60)
        print("  PASTE THIS INTO YOUR .env FILE:")
        print(f"  QWEN_API_URL={url}/generate")
        print("="*60 + "\n")
        break